name: sebi
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sebi_logo.png

fonts:
  - family: Nunito
    fonts:
      - asset: fonts/Nunito-Regular.ttf
      - asset: fonts/Nunito-Italic.ttf
        style: italic
      - asset: fonts/Nunito-Bold.ttf
        weight: 700
      - asset: fonts/Nunito-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: fonts/Nunito-Light.ttf
        weight: 300
      - asset: fonts/Nunito-LightItalic.ttf
        weight: 300
        style: italic
      - asset: fonts/Nunito-SemiBold.ttf
        weight: 600
